---
title: "Stroop Demo"
author: "Matthew Crump"
output:
  html_document:
    mathjax: null
    highlight: null
    theme: null
    css: jspsych-6/css/jspsych.css
    includes:
      in_header: plugins.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r}
# load jspsych and plugin scripts
library(htmltools)
tagList(
tags$script(src='jspsych-6/jspsych.js'),
tags$script(src='jspsych-6/plugins/jspsych-html-keyboard-response.js'),
tags$script(src='xprmntr/xprmntr.js')
)
```


```{r, results="asis"}
# Define stimuli in R, output as script 
library(xprmntr)
library(dplyr)

# create dataframe to define stimuli
stroop_stim <- data.frame( stimulus = length(16),
                           word = rep(c("red","green","blue","yellow"), each=4),
                           color = rep(c("red","green","blue","yellow"), 4),
                           response = rep(c("r","g","b","y"), 4),
                           stim_type = length(16),
                           id = "stroop_stim",
                           fontsize = "60pt") %>%
  mutate(stim_type = as.numeric(word==color)) %>%
  mutate(stim_type = recode(stim_type, `1` = "congruent", `0` = "incongruent"))

# write html definitions to the stimulus column
# note this could be added as a pipe to the above, setting df=.
stroop_stim$stimulus <- html_stimulus(df = stroop_stim, 
                                html_content = "word",
                                html_element = "p",
                                column_names = c("color","fontsize"),
                                css = c("color", "font-size"),
                                id = "id")

# create json object from dataframe
stimulus_json <- stimulus_df_to_json(df = stroop_stim,
                                     stimulus = "stimulus",
                                     data = c("word","color","response","stim_type"))

# write json object to script
write_to_script(stimulus_json,"test_stimuli")

```


```{js}
/* experiment parameters */
var reps_per_trial_type = 1;

/*set up welcome block*/
var welcome = {
  type: "html-keyboard-response",
  stimulus: "Welcome to the experiment. Press any key to begin."
};

/*set up instructions block*/
var instructions = {
  type: "html-keyboard-response",
  stimulus: "<p>In this task, you will see word in a color</p>"+
    "<p style='color:red;font-size:60pt;'>BLUE</p>"+
    "<p>Press r, g, b, or y to identify the color, not the word</p>"+
    "<p>E.g., press r for red in this example</p>"+
    "<p>Press any key to begin.</p>",
  post_trial_gap: 1000
};


/* defining test timeline */
var test = {
  timeline: [{
    type: 'html-keyboard-response',
    choices: ["r","g","b","y"],
    trial_duration: 2000,
    response_ends_trial: true,
    stimulus: jsPsych.timelineVariable('stimulus'),
    data: jsPsych.timelineVariable('data'),
    on_finish: function(data){
      var correct = false;
      if(data.response == 'r' &&  data.key_press == 82 && data.rt > -1){
        correct = true;
      } else if(data.response == 'g' &&  data.key_press == 71 && data.rt > -1){
        correct = true;
      } else if(data.response == 'b' &&  data.key_press == 66 && data.rt > -1){
        correct = true;
      } else if(data.response == 'y' &&  data.key_press == 89 && data.rt > -1){
        correct = true;
      }
      data.correct = correct;
    },
    post_trial_gap: function() {
        return Math.floor(Math.random() * 1500) + 500;
    }
  }],
  timeline_variables: test_stimuli,
  sample: {type: 'fixed-repetitions', size: reps_per_trial_type}
};

/*defining debriefing block*/
var debrief = {
  type: "html-keyboard-response",
  stimulus: function() {
    var total_trials = jsPsych.data.get().filter({trial_type: 'html-keyboard-response'}).count();
    var accuracy = Math.round(jsPsych.data.get().filter({correct: true}).count() / (total_trials-2) * 100);
    var congruent_rt = Math.round(jsPsych.data.get().filter({correct: true, stim_type: 'congruent'}).select('rt').mean());
    var incongruent_rt = Math.round(jsPsych.data.get().filter({correct: true, stim_type: 'incongruent'}).select('rt').mean());
    return "<p>You responded correctly on <strong>"+accuracy+"%</strong> of the trials.</p> " +
    "<p>Your average response time for congruent trials was <strong>" + congruent_rt + "ms</strong>.</p>"+
    "<p>Your average response time for incongruent trials was <strong>" + incongruent_rt + "ms</strong>.</p>"+
    "<p>Press any key to complete the experiment. Thank you!</p>";
  }
};

/*set up experiment structure*/
var timeline = [];
timeline.push(welcome);
timeline.push(instructions);
timeline.push(test);
timeline.push(debrief);

/*start experiment*/
jsPsych.init({
    timeline: timeline,
    on_finish: function() {
        xprmntr.save_locally();
    }
});
```


