---
title: "Experiment 1 Analysis"
author: "Matt Crump"
date: "10/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r}
library(tidyverse)
library(data.table)
```


## Load data

```{r}
all_data <- rbindlist(lapply(list.files(path="../experiments/Experiment 1/data",
                                      pattern = "\\.csv",
                                      full.names = TRUE), 
                           fread))
```

## Checks

```{r}
check_summary <- all_data %>%
  filter(is.na(stim_type) == FALSE,
         rt != "null") %>%
  mutate(rt = as.numeric(rt)) %>%
  group_by(file_id) %>%
  summarise(trial_count = n(),
            accuracy = mean(correct),
            mean_rt = mean(rt))

knitr::kable(check_summary)
  
```

## Analysis

```{r}
# get individual subject mean RTs
subject_means <- all_data %>%
  filter(is.na(stim_type) == FALSE,
         correct == TRUE,
         rt != "null") %>%
  mutate(file_id = as.factor(file_id),
         stim_type = as.factor(stim_type),
         rt = as.numeric(rt)) %>%
  group_by(file_id,stim_type) %>%
  summarise(subject_mean_rt = mean(rt))

# get global average of subject mean RTs and SEMs
plot_means <- subject_means %>%
  group_by(stim_type) %>%
  summarise(mean_rt = mean(subject_mean_rt),
            sem = sd(subject_mean_rt)/sqrt(length(subject_mean_rt)))

# bar plot
ggplot(plot_means, aes(x=stim_type,y=mean_rt))+
  geom_bar(stat="identity", position="dodge")+
  geom_errorbar(aes(ymin = mean_rt-sem,
                    ymax = mean_rt+sem),
                position = "dodge", width = 0.25)+
  xlab("congruency")+
  ylab("Mean RT (ms)")+
  theme_classic()

# table

knitr::kable(plot_means)

# ANOVA


aov_out <- aov(subject_mean_rt ~ stim_type + Error(file_id/stim_type), subject_means)
summary(aov_out)

```



